# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Deploy this DaemonSet to configure kubelet on nodes with the
# "cloud.google.com/gke-spot=true" label.
#
# WARNING: Changing the kubelet configuration requires a kubelet
# restart.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-spot
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kubelet-spot
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kubelet-spot
    spec:
      tolerations:
      - operator: Exists
      volumes:
      - name: host
        hostPath:
          path: /
      hostPID: true
      initContainers:
      - name: kubelet-spot
        image: debian
        env:
        - name: KUBELET_CONF_FILE
          value: "/host/home/kubernetes/kubelet-config.yaml"
        command:
        - /bin/bash
        - -c
        - |
          set -xeuo pipefail

          function set-kubelet-config() {
            echo 'Editing kubelet config file'
            sed -i "s/GracefulNodeShutdown: true/GracefulNodeShutdown: false/g" ${KUBELET_CONF_FILE}
            sed -i "s/shutdownGracePeriod: 30s/shutdownGracePeriod: 0s/g"  ${KUBELET_CONF_FILE}
            sed -i "s/shutdownGracePeriodCriticalPods: 15s/shutdownGracePeriodCriticalPods: 0s/g" ${KUBELET_CONF_FILE}

          }

          set-kubelet-config
          echo "Restarting kubelet..."
          chroot /host nsenter -a -t1 -- systemctl restart kubelet.service
          echo "Success!"
        volumeMounts:
        - name: host
          mountPath: /host
        resources:
          requests:
            memory: 5Mi
            cpu: 5m
        securityContext:
          privileged: true
      containers:
      - image: gcr.io/google-containers/pause:3.2
        name: pause
      # Ensures that the pods will only run on the nodes having the correct
      # label.
      nodeSelector:
        "cloud.google.com/gke-spot": "true"
